name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install

    - name: Build React App
      run: npm run build

    - name: Deploy to Remote Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_SERVER_HOST }}
        username: ${{ secrets.REMOTE_SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Move to the directory where the site files are located
          cd /var/www/earth-network-app

          # Remove old build files
          rm -rf *

          # Upload new build files from the GitHub runner
          scp -r ./build/* ${{ secrets.REMOTE_SERVER_USERNAME }}@${{ secrets.REMOTE_SERVER_HOST }}:/var/www/earth-network-app/

          # Restart NGINX to apply the changes
          sudo systemctl restart nginx
