name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deploy and Build on Remote Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_SERVER_HOST }}
        username: ${{ secrets.REMOTE_SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Navigate to the project directory
          cd /var/www/earth-network-app

          # Pull the latest changes from the repository
          git pull origin main

          # Install dependencies
          npm install

          # Build the project
          npm run build

          # Remove old files and move build output to the correct location
          sudo rm -rf /var/www/earth-network-app/build/*
          mv build/* /var/www/earth-network-app/

          # Restart NGINX to apply the changes
          sudo systemctl restart nginx
